README.md
=> Remove links to wrong locations.

bin/matrix-deploy.js, lib/helpers.js
This was initially an update for deployment, since the deployment cycle is being reviewed this is probably good for matrix publish
=> Policy and version adjustments, possible progress for matrix publish

bin/matrix-register.js
- Loader for matrix register
- Fixed "Device registered succesfully" typo
- Stop execution if secret retrieval fails
=> Loader for matrix register, typo and process exit

bin/matrix-init.js, config/locales/en.yml, lib/app.js
- Start, stop and restart error handling
- Added en error strings for start, stop and restart
- Updated default (rc) bucket URL
Addresses
=> Handle error on app socket and fix default bucket url

bin/matrix-publish.js, lib/helpers.js
It could be cleaner but it server for the purpose of testing this implementation
=> Add readme upload to publication

bin/matrix, bin/matrix-login.js, bin/matrix-register.js
Alert users when no connection is available or servers are down
=> Connectivity errors overall (login, register)

bin/matrix-deploy.js, bin/matrix-install.js, lib/helpers.js
Deploy version confirmation removed, Install policy printed before specifying policy preferences
=> Remove version check on deploy, print policy on install

bin/matrix-list.js, lib/app.js, package.json
- Use **package-json** module to retrieve the latest version for the **matrix-cli** module. If current version doesn't match, show available update message.
- App listing was failing when `Matrix.firebase.app.list` returned _null_
=> npm package version check, matrix list apps validation

lib/helpers.js
If app has no policy, it doesn't ask for permissions on installation
=> Don't ask for policy settings on install when the app doesn't require so

HISTORY.md, bin/matrix-remove.js, config/locales/en.yml, lib/app.js, lib/helpers.js
Adds `matrix remove` and `matrix remove <id>`, those commands allow the removal of devices.
The command will use the currently selected device or the one specified and will show a confirmation message before removing it if it does exist.
_Requires **matrix-firebase** `dr/remove` update._
=> matrix remove

config/locales/en.yml, lib/app.js
matrix start, stop and restart ACK using app status
=> matrix start, stop and restart ACK using app status

config/locales/en.yml, lib/app.js
add timeouts in start, stop and restart commands
=> add timeouts in start, stop and restart commands

bin/matrix-install.js, bin/matrix-update.js, config/locales/en.yml
add support for command update and refactoring  the command for install for support version.
=> support for command update and install

bin/matrix-create.js
catch the error if the process is canceled and exit.
=> catch the error if the process is canceled and exit.

bin/matrix-create.js, bin/matrix-publish.js, lib/helpers.js
- Add description, keywords, categories to appstore node from config.yaml
- matrix create err check to stop crash
- Don't ask for a selected device when deploying
=> config.yaml description, matrix create fix, no device deploy

bin/matrix-create.js, bin/matrix-deploy.js, bin/matrix-init.js, bin/matrix-install.js, bin/matrix-login.js, bin/matrix-publish.js, bin/matrix-register.js, bin/matrix-remove.js, bin/matrix-search.js, bin/matrix-set.js, bin/matrix-uninstall.js, bin/matrix-use.js, lib/app.js, lib/helpers.js, test/_functions.js, test/_runner.js, test/terminal.test.js
@diegoribero please take a look at this, use an rc user. there is some funkiness when you switch users. we save the value to firebase. value is saved to config.user.trackOk. check with `matrix debug`
=> Add Keen IO events and fix search

bin/matrix-deploy.js, bin/matrix-publish.js, lib/helpers.js
On **deploy** and **publish**, the app's config.yaml is validated using **matrix-app-config-helper**, if it fails the process is stopped
=> Validate config on deploy and publish

lib/helpers.js
Makes sure keywords are properly formed arrays
- Removes duplicated keywords
- Makes each keyword startCase
- Trims keywords
- Removes empty keywords
=> Parse keywords string to array

bin/matrix-create.js
Add a startCase version of the **name** called **displayName** on app creation (**matrix create**)
=> Apps displayName on creation

bin/matrix-publish.js
Now is not necesary select on device for publish an APP!
=> Fix  issue with publis .

bin/matrix-set.js, config/environments.js
migrate enviromentes to other file And also fix any issues with validation of the enviroments  And  add color in the log ..  More presentable !
=> migrate enviromentes !

lib/helpers.js
=> fix small issue with appDetails And log error

bin/matrix-create.js, lib/helpers.js
Now save the name of the app how name in the package.json
=> fix package.json

bin/matrix-init.js, bin/matrix-login.js, lib/helpers.js
Adding trackuserok to stop asking share usage info when permission had already being granted
=> [MX-43] Don't ask to share usage info if I've already granted permission.

bin/matrix-list.js
Fixing default status condition. When status exists status was setting default to inactive.
=> MX-49 - online status

bin/matrix-register.js
Moving logic to function login. Basically calling logout function before login after registration.
=> MX-137 CLI - Registering new user doesn't clear old device
